### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by HastingsGreer** [HastingsGreer/footsteps#4]

**Comment by tbirdso** [comment]
Hi @HastingsGreer , sorry for the delay! Here is what I'm seeing when trying to set up a training run for the ICON 2D triangles example:

```
(venv-itk) C:\repos\ICON>python training_scripts\2d_triangles_example.py
Input name of run:
footsteps-test-1
Traceback (most recent call last):
  File "training_scripts\2d_triangles_example.py", line 15, in <module>
    import footsteps
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\footsteps\__init__.py", line 1, in <module>
    from footsteps.footsteps import output_dir
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\site-packages\footsteps\footsteps.py", line 17, in <module>
    f.write(subprocess.check_output(["which", "python"]).decode())
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\tom.birdsong\Anaconda3\envs\venv-itk\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

It looks like the issue is that `which python`, called at [https://github.com/HastingsGreer/footsteps/blob/master/src/footsteps/footsteps.py#L27](https://github.com/HastingsGreer/footsteps/blob/master/src/footsteps/footsteps.py#L27) is platform dependent. See a suggested fix [here](https://stackoverflow.com/questions/647515/how-can-i-find-where-python-is-installed-on-windows).

**Comment by tbirdso** [comment]
This resolves the issue, thanks!
